const properties = [
    {
      id: 1,
      title: "Plot No. 39, G. No.286, S. No. 107/2 B/h Punjab aba Govardhan College",
      address: "Flat No. 705 , 7th floor, V. N. Pride, Nashik City-422003",
      price: 120000,
      category: "Residential",
          bankName: "Yes Bank",
    time:"10am-12am",
      area: "1200 sq.ft",
      auctionDate: "2025-02-15",
      imageUrl: "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      profileImage: 'YesBank.png',

    },
    // {
    //   id: 2,
    //   title: "Beachside Villa",
    //   address: "Pune",
    //   price: 250000,
    //   category: "Residential",
    //       bankName: "Yes Bank",
    // time:"10am-12am",
    //   area: "3000 sq.ft",
    //   auctionDate: "2025-02-13",
    //   imageUrl: "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
    //   profileImage: 'YesBank.png',

    // },
    // {
    //   id: 3,
    //   title: "Downtown Office",
    //   address: "Mumbai",
    //   price: 350000,
    //   category: "Commercial",
    //       bankName: "Yes Bank",
    // time:"10am-12am",
    //   area: "5000 sq.ft",
    //   auctionDate: "2025-02-25",
    //   imageUrl: "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
    //   profileImage: 'YesBank.png',

    // },
    // {
    //   id: 4,
    //   title: "Suburban House",
    //   address: "Goa",
    //   price: 180000,
    //   category: "Residential",
    //       bankName: "Yes Bank",
    // time:"10am-12am",
    //   area: "2000 sq.ft",
    //   auctionDate: "2025-02-28",
    //   imageUrl: "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
    //   profileImage: 'YesBank.png',

    // },
    // {
    //   id: 5,
    //   title: "Warehouse Space",
    //   address: "Delhi",
    //   price: 400000,
    //   category: "Industrial",
    //       bankName: "Yes Bank",
    // time:"10am-12am",
    //   area: "10000 sq.ft",
    //   auctionDate: "2025-03-10",
    //   imageUrl: "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
    //   profileImage: 'YesBank.png',

    // },
  ];
export default properties;
  

  export const singlePostData = [{
    id: 1,
    title: "Prafull Sales Corporation:Residental Flat",
    price: '48,36,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
    ],
    latitude: 20.19227,
    longitude: 73.74559,
    auctionDate: "2025-01-15",
    time:"10am-12am",
    area: "1832 Sq. Ft.",
    bankName: "Union Bank",
    city: "Nashik",
    state:"Maharashtra",
    category: 'Residential',
    address: "Flat No. 705 , 7th floor, V. N. Pride, CTS No. 5984, S. No. 148/9, Nashik City-422003 ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "All the part and parcel of land & building in the name of Prafull Sales Corporation: Residential Flat No. 705 admeasuring 1832 Sq. Ft. 7th floor, V. N. Pride, CTS No. 5984, S. No. 148/9, Nashik City-422003",
    enquiryUrl:"https://baanknet.com ",
    contactNo:"8169178780", 
    borrower: "M/s Prafull Sales",
    dueAmount:"2,40,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"50,000",
    auctionType:"E-auction",
    inspectDate:"10/01/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
{
    id: 2,
    title: "Plot No. 39, G. No.286, S. No. 107/2 B/h Punjab aba Govardhan College",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    latitude: 20.009444549124982,
    longitude: 73.79983966123419,
    auctionDate: "2025-02-13",
    area: "435.25(sq. m)",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Nashik",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "Plot No. 39, G. No.286, S. No. 107/2 B/h Punjab aba Govardhan College, Nashik. Nashik-Mumbai Highway Village Take Ghoti, Tal. Igatpuri, Dist. Nashik ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Plot No. 39, G. No.286, S. No. 107/2 B/h Punjab aba Govardhan College, Nashik. Nashik-Mumbai Highway Village Take Ghoti, Tal. Igatpuri, Dist. Nashik admeasuring 435.25 sqm. belonging to Satish Jagannath Yewale.",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "Satish Jagannath Yewale",
    dueAmount:"1,50,55,879",
    reservPrice:"48,36,000", 
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 3,
    title: "Plot No.48, G. No.286, S. No. 107/2 B/h Punjab Aba Govardhane College",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 20.009444549124982,
    longitude: 73.79983966123419,
    auctionDate: "2025-02-17",
    area: " 329 Sq. Mt.",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Industrial',
    contact:'9137450148',
    address: "Plot No.48, G. No.286, S. No. 107/2 B/h Punjab Aba Govardhane College, Nashik. Nashik-Mumbai Highway Village Take Ghoti, Igatpuri,Nashik ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Plot No.48, G. No.286, S. No. 107/2 B/h Punjab Aba Govardhane College, Nashik. Nashik-Mumbai Highway Village Take Ghoti, Ta. Igatpuri, Dist. Nashik admeasuring ( 329 Sq. Mt. belonging to Satish Jagannath Yevale",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "Satish Jagannath Yevale",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 4,
    title: "Plot No. 49, G. No.286, S. No. 107/2 B/h",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 20.009444549124982,
    longitude: 73.79983966123419,
    auctionDate: "2025-02-15",
    area: " 357sq.m.",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "Plot No. 49, G. No.286, S. No. 107/2 B/h Punjab aba Govardhane College, Nashik.",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Plot No. 49, G. No.286, S. No. 107/2 B/h Punjab aba Govardhane College, Nashik. Nashik-Mumbai Highway Village Take Ghoti, Ta. Igatpuri, Dist. Nashik admeasuring 357sq.m. belonging to Satish Jagannath Yewale",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 5,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-01-1",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Residential',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "N.A. Plots bearing numbers 1 to 10, out of Gat No. 37/3, Village Shastrinagar, Nandgaon-Manmad Road, Tal.. Nandgaon, Dist. Nashik. Admeasuring 7109.73 Sq. Mt.",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 6,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-02-15",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 7,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-02-15",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 8,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-02-15",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 9,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-02-1",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Residential',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 10,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-02-15",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Agricultural',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 11,
    title: "An Awesome Mumbai Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-01-12",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Mumbai",
    state:"Maharashtra",
    category: 'Commercial',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"8/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  {
    id: 12,
    title: "An Awesome Pune Villa!",
    price: '50,00,000',
    media: [
      "https://img.vistarooms.com/gallery/thumbnail/grey-mosaics-144ce1.jpg",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "/S8.mp4",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
  
    latitude: 18.9535,
    longitude: 72.8165,
    auctionDate: "2025-2-9",
    area: "200 sq.ft",
    bankName: "Yes Bank",
    time:"10am-12am",
    city: "Pune",
    state:"Maharashtra",
    category: 'Agricultural',
    contact:'9137450148',
    address: "1234 Charni Road, Mumbai ",
    nearbyPlace:"Dmart(1km away),AB School(200m away),",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
    enquiryUrl:"www.google.com",
    contactNo:"9169178550", 
    borrower: "M/s Vijay Sales",
    dueAmount:"1,50,55,879", 
    reservPrice:"48,36,000",
    deposit:"10% of the reserve price",
    bidInc:"25,000",
    auctionType:"E-auction",
    inspectDate:"16/02/2025",
    inspectTime:"12.00 NOON to 5.00 PM",
    message:"All bidders are requested to visit the above site & complete the registration, KYC updation & payment 3 to 4 days before date of E-auction to avoid last minute rush"
  },
  ]

